#!/bin/bash
# ═══════════════════════════════════════════════
# HelixCD Mobile Access Setup
# Generates GitHub Pages prompt page
# Works when laptop is OFF
# Mobile just opens URL and taps copy
# ═══════════════════════════════════════════════

set -e

export PYTHONUTF8=1
export PYTHONIOENCODING=utf-8

WORKSPACE="$HOME/helixcd-workspace"
REPO="$WORKSPACE/helixcd"
VISION="$WORKSPACE/helixcd-vision"
GITHUB_USER="ShamshabadAnil"

echo ""
echo "============================================"
echo "  HelixCD Mobile Access Setup"
echo "============================================"
echo ""

# ════════════════════════════════════════════════
# FILE 1 — GITHUB PAGES HTML
# The mobile prompt page
# Auto-generated by GitHub Actions
# ════════════════════════════════════════════════
echo "[DIR] Creating GitHub Pages structure..."

mkdir -p "$REPO/docs"

cat > "$REPO/docs/index.html" << 'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
    content="width=device-width,
    initial-scale=1.0,
    maximum-scale=1.0">
  <meta name="theme-color" content="#0f172a">
  <title>HelixCD — Agent Prompt</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      -webkit-tap-highlight-color: transparent;
    }

    body {
      font-family: -apple-system,
        BlinkMacSystemFont,
        'Segoe UI', sans-serif;
      background: #0f172a;
      color: #e2e8f0;
      min-height: 100vh;
      padding: 16px;
    }

    .header {
      text-align: center;
      padding: 20px 0 16px;
      border-bottom: 1px solid #1e293b;
      margin-bottom: 20px;
    }

    .logo {
      font-size: 13px;
      font-weight: 700;
      letter-spacing: 3px;
      color: #38bdf8;
      text-transform: uppercase;
      margin-bottom: 4px;
    }

    .subtitle {
      font-size: 11px;
      color: #475569;
    }

    .status-bar {
      display: flex;
      gap: 8px;
      margin-bottom: 16px;
      flex-wrap: wrap;
    }

    .badge {
      font-size: 11px;
      padding: 4px 10px;
      border-radius: 20px;
      font-weight: 600;
    }

    .badge-phase {
      background: #1e3a5f;
      color: #38bdf8;
    }

    .badge-progress {
      background: #1a2e1a;
      color: #4ade80;
    }

    .badge-updated {
      background: #1e1e2e;
      color: #94a3b8;
      font-weight: 400;
    }

    .task-card {
      background: #1e293b;
      border: 1px solid #334155;
      border-radius: 12px;
      padding: 16px;
      margin-bottom: 16px;
    }

    .task-label {
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 2px;
      color: #475569;
      text-transform: uppercase;
      margin-bottom: 8px;
    }

    .task-name {
      font-size: 18px;
      font-weight: 700;
      color: #f1f5f9;
      line-height: 1.3;
      margin-bottom: 4px;
    }

    .task-id {
      font-size: 12px;
      color: #38bdf8;
      font-family: monospace;
    }

    .progress-bar {
      height: 6px;
      background: #1e293b;
      border-radius: 3px;
      margin: 16px 0;
      overflow: hidden;
      border: 1px solid #334155;
    }

    .progress-fill {
      height: 100%;
      background: linear-gradient(
        90deg, #0ea5e9, #38bdf8
      );
      border-radius: 3px;
      transition: width 0.5s ease;
    }

    .prompt-section {
      margin-bottom: 16px;
    }

    .prompt-label {
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 2px;
      color: #475569;
      text-transform: uppercase;
      margin-bottom: 8px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .token-count {
      font-size: 10px;
      color: #4ade80;
      font-weight: 600;
    }

    .prompt-box {
      background: #0f172a;
      border: 1px solid #334155;
      border-radius: 8px;
      padding: 14px;
      font-family: 'SF Mono', Monaco,
        'Courier New', monospace;
      font-size: 11px;
      line-height: 1.6;
      color: #94a3b8;
      white-space: pre-wrap;
      word-break: break-word;
      max-height: 240px;
      overflow-y: auto;
      -webkit-overflow-scrolling: touch;
    }

    .copy-btn {
      width: 100%;
      padding: 18px;
      background: #0ea5e9;
      color: white;
      border: none;
      border-radius: 12px;
      font-size: 17px;
      font-weight: 700;
      cursor: pointer;
      margin-bottom: 12px;
      transition: all 0.15s ease;
      letter-spacing: 0.5px;
    }

    .copy-btn:active {
      transform: scale(0.98);
      background: #0284c7;
    }

    .copy-btn.copied {
      background: #16a34a;
    }

    .copy-btn.copied::before {
      content: "Copied! Now paste into ";
    }

    .paste-hint {
      text-align: center;
      font-size: 12px;
      color: #475569;
      margin-bottom: 20px;
    }

    .paste-hint span {
      color: #38bdf8;
      font-weight: 600;
    }

    .agents-row {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 8px;
      margin-bottom: 20px;
    }

    .agent-btn {
      padding: 14px;
      border-radius: 10px;
      border: 1px solid #334155;
      background: #1e293b;
      color: #e2e8f0;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      text-align: center;
      transition: all 0.15s;
      text-decoration: none;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 6px;
    }

    .agent-btn:active {
      background: #2d3f55;
      transform: scale(0.97);
    }

    .memory-section {
      background: #1e293b;
      border: 1px solid #334155;
      border-radius: 12px;
      padding: 14px;
      margin-bottom: 16px;
    }

    .memory-label {
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 2px;
      color: #475569;
      text-transform: uppercase;
      margin-bottom: 10px;
    }

    .memory-item {
      font-size: 12px;
      color: #94a3b8;
      padding: 6px 0;
      border-bottom: 1px solid #0f172a;
      line-height: 1.5;
    }

    .memory-item:last-child {
      border-bottom: none;
    }

    .refresh-btn {
      width: 100%;
      padding: 12px;
      background: transparent;
      border: 1px solid #334155;
      border-radius: 10px;
      color: #475569;
      font-size: 13px;
      cursor: pointer;
      margin-bottom: 16px;
    }

    .refresh-btn:active {
      background: #1e293b;
      color: #94a3b8;
    }

    .footer {
      text-align: center;
      font-size: 11px;
      color: #334155;
      padding: 16px 0;
    }

    .toast {
      position: fixed;
      bottom: 30px;
      left: 50%;
      transform: translateX(-50%);
      background: #16a34a;
      color: white;
      padding: 12px 24px;
      border-radius: 24px;
      font-size: 14px;
      font-weight: 600;
      opacity: 0;
      transition: opacity 0.3s;
      pointer-events: none;
      z-index: 999;
      white-space: nowrap;
    }

    .toast.show {
      opacity: 1;
    }

    @media (min-width: 480px) {
      body { max-width: 440px; margin: 0 auto; }
    }
  </style>
</head>
<body>

  <div class="header">
    <div class="logo">HelixCD</div>
    <div class="subtitle">
      Agent Prompt · Tap to copy
    </div>
  </div>

  <div class="status-bar">
    <span class="badge badge-phase"
      id="phase">documentation</span>
    <span class="badge badge-progress"
      id="progress-badge">0/181</span>
    <span class="badge badge-updated"
      id="updated">updating...</span>
  </div>

  <div class="task-card">
    <div class="task-label">Current Task</div>
    <div class="task-name" id="task-name">
      Loading...
    </div>
    <div class="task-id" id="task-id"></div>
  </div>

  <div class="progress-bar">
    <div class="progress-fill"
      id="progress-fill"
      style="width: 0%">
    </div>
  </div>

  <div class="prompt-section">
    <div class="prompt-label">
      Agent Prompt
      <span class="token-count"
        id="token-count">
        ~0 tokens
      </span>
    </div>
    <div class="prompt-box" id="prompt-box">
      Loading prompt...
    </div>
  </div>

  <button class="copy-btn"
    id="copy-btn"
    onclick="copyPrompt()">
    Tap to Copy Prompt
  </button>

  <div class="paste-hint">
    Then paste into
    <span>Claude</span> or
    <span>Cursor</span>
  </div>

  <div class="agents-row">
    <a class="agent-btn"
      href="https://claude.ai"
      target="_blank">
      Claude
    </a>
    <a class="agent-btn"
      href="https://cursor.sh"
      target="_blank">
      Cursor
    </a>
  </div>

  <div class="memory-section">
    <div class="memory-label">
      Last Sessions
    </div>
    <div id="memory-list">
      <div class="memory-item">
        Loading...
      </div>
    </div>
  </div>

  <button class="refresh-btn"
    onclick="loadData()">
    Refresh
  </button>

  <div class="footer">
    HelixCD · Owner: ShamshabadAnil
  </div>

  <div class="toast" id="toast">
    Copied!
  </div>

  <script>
    // Data injected by GitHub Actions
    // Falls back to data.json
    const DATA_URL = './data.json';

    let currentPrompt = '';

    async function loadData() {
      try {
        const res = await fetch(
          DATA_URL + '?t=' + Date.now()
        );
        const data = await res.json();
        renderData(data);
      } catch(e) {
        document.getElementById('task-name')
          .textContent = 'Could not load data';
        document.getElementById('task-name')
          .style.color = '#ef4444';
      }
    }

    function renderData(data) {
      // Task
      const taskName = document.getElementById(
        'task-name'
      );
      const taskId = document.getElementById(
        'task-id'
      );
      taskName.textContent =
        data.task_name || 'No task found';
      taskId.textContent =
        data.task_id
        ? 'ID: ' + data.task_id
        : '';

      // Progress
      const done = data.progress_done || 0;
      const total = data.progress_total || 181;
      const pct = data.progress_percent || 0;

      document.getElementById('progress-badge')
        .textContent = done + '/' + total;
      document.getElementById('progress-fill')
        .style.width = pct + '%';

      // Phase
      document.getElementById('phase')
        .textContent = data.phase || 'docs';

      // Updated
      const updated = data.updated
        ? new Date(data.updated)
            .toLocaleString('en',{
              month:'short',
              day:'numeric',
              hour:'2-digit',
              minute:'2-digit'
            })
        : 'unknown';
      document.getElementById('updated')
        .textContent = updated;

      // Prompt
      const prompt = data.prompt || '';
      currentPrompt = prompt;
      document.getElementById('prompt-box')
        .textContent = prompt;

      // Token count
      const tokens = Math.round(
        prompt.length / 4
      );
      document.getElementById('token-count')
        .textContent = '~' + tokens + ' tokens';

      // Memory
      const memory = data.memory || [];
      const memList = document.getElementById(
        'memory-list'
      );
      if (memory.length > 0) {
        memList.innerHTML = memory
          .slice(-3)
          .map(m =>
            '<div class="memory-item">'
            + m + '</div>'
          )
          .join('');
      } else {
        memList.innerHTML =
          '<div class="memory-item">' +
          'No sessions yet</div>';
      }
    }

    function copyPrompt() {
      if (!currentPrompt) return;

      const btn = document.getElementById(
        'copy-btn'
      );
      const toast = document.getElementById(
        'toast'
      );

      // Try modern clipboard API
      if (navigator.clipboard) {
        navigator.clipboard
          .writeText(currentPrompt)
          .then(() => showCopied(btn, toast))
          .catch(() => fallbackCopy(btn, toast));
      } else {
        fallbackCopy(btn, toast);
      }
    }

    function fallbackCopy(btn, toast) {
      // Create temp textarea
      const ta = document.createElement(
        'textarea'
      );
      ta.value = currentPrompt;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.focus();
      ta.select();

      try {
        document.execCommand('copy');
        showCopied(btn, toast);
      } catch(e) {
        // Manual select fallback
        ta.style.opacity = '1';
        ta.style.position = 'static';
        ta.style.width = '100%';
        ta.style.height = '120px';
        ta.style.fontSize = '14px';
        btn.textContent =
          'Select all text above and copy';
      }

      document.body.removeChild(ta);
    }

    function showCopied(btn, toast) {
      btn.classList.add('copied');
      btn.textContent =
        'Copied! Paste into Claude or Cursor';
      toast.classList.add('show');

      setTimeout(() => {
        btn.classList.remove('copied');
        btn.textContent = 'Tap to Copy Prompt';
        toast.classList.remove('show');
      }, 3000);
    }

    // Load on start
    loadData();

    // Auto refresh every 5 minutes
    setInterval(loadData, 300000);
  </script>
</body>
</html>
HTMLEOF

echo "  [OK] docs/index.html"

# ════════════════════════════════════════════════
# FILE 2 — DATA GENERATOR (Python)
# Generates data.json from repos
# Run by GitHub Actions automatically
# ════════════════════════════════════════════════
echo "[DIR] Creating data generator..."

cat > "$REPO/scripts/generate_mobile_data.py" \
<< 'EOF'
#!/usr/bin/env python3
"""
HelixCD Mobile Data Generator.

Generates data.json for the mobile
prompt page. Run by GitHub Actions
after every helix done commit.

Output: docs/data.json
"""
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path


# ── PATHS ──────────────────────────────────────
WORKSPACE = Path(
    os.environ.get(
        "GITHUB_WORKSPACE",
        str(Path.home() / "helixcd-workspace")
    )
)

REPO = WORKSPACE / "helixcd"
VISION = WORKSPACE / "helixcd-vision"
OUTPUT = REPO / "docs" / "data.json"


def get_next_task(
    registry: Path
) -> dict:
    """Get next task from work registry.

    Args:
        registry: Path to WORK_REGISTRY.md.

    Returns:
        Task dictionary.
    """
    if not registry.exists():
        return {
            "id": "01",
            "name": "Product Vision",
            "status": "not_started"
        }

    with open(registry, encoding="utf-8") as f:
        content = f.read()

    # In progress first
    patterns = [
        (r'\|\s*(\S+)\s*\|([^|]+)\|[^|]*'
         r'In Progress[^|]*\|', "in_progress"),
        (r'\|\s*(\S+)\s*\|([^|]+)\|[^|]*'
         r'Not Started[^|]*\|', "not_started"),
        (r'\|\s*(\S+)\s*\|([^|]+)\|[^|]*'
         r'[Ww][Ii][Pp][^|]*\|', "in_progress"),
        (r'\|\s*(\S+)\s*\|([^|]+)\|[^|]*'
         r'\[TODO\][^|]*\|', "not_started"),
    ]

    for pattern, status in patterns:
        matches = re.findall(pattern, content)
        if matches:
            return {
                "id": matches[0][0].strip(),
                "name": matches[0][1].strip(),
                "status": status
            }

    return {
        "id": "done",
        "name": "All tasks complete!",
        "status": "complete"
    }


def get_progress(
    registry: Path
) -> dict:
    """Get project progress statistics.

    Args:
        registry: Path to WORK_REGISTRY.md.

    Returns:
        Progress statistics dictionary.
    """
    if not registry.exists():
        return {
            "done": 0,
            "total": 181,
            "percent": 0
        }

    with open(registry, encoding="utf-8") as f:
        content = f.read()

    done = (
        content.count("[APPROVED]") +
        content.count("[DONE]") +
        content.count("Completed") +
        len(re.findall(r'🔵|🟢', content))
    )
    total_markers = (
        content.count("[TODO]") +
        content.count("[WIP]") +
        content.count("Not Started") +
        content.count("In Progress") +
        len(re.findall(r'🔴|🟡', content))
    )
    total = max(done + total_markers, 181)
    pct = int(done * 100 / total) if total else 0

    return {
        "done": done,
        "total": total,
        "percent": pct
    }


def get_memory(vision: Path) -> list:
    """Get last 3 session summaries.

    Args:
        vision: Path to helixcd-vision.

    Returns:
        List of memory summary strings.
    """
    memory_file = vision / "MEMORY_LOG.md"

    if not memory_file.exists():
        return ["No previous sessions"]

    with open(
        memory_file, encoding="utf-8"
    ) as f:
        content = f.read()

    sessions = re.findall(
        r'## SESSION_\d+.*?(?=## SESSION_|\Z)',
        content,
        re.DOTALL
    )

    summaries = []
    for s in sessions[-3:]:
        agent_m = re.search(
            r'agent:\s*(.+)', s
        )
        done_m = re.search(
            r'### completed\n(.+?)(?=###|\Z)',
            s, re.DOTALL
        )
        date_m = re.search(
            r'date:\s*(.+)', s
        )

        parts = []
        if date_m:
            parts.append(
                date_m.group(1).strip()[:10]
            )
        if agent_m:
            parts.append(
                agent_m.group(1).strip()
            )
        if done_m:
            first = done_m.group(1)\
                .strip().split('\n')[0]
            parts.append(first[:60])

        if parts:
            summaries.append(
                " | ".join(parts)
            )

    return summaries or ["No sessions yet"]


def build_prompt(
    task: dict,
    progress: dict,
    memory: list
) -> str:
    """Build minimal agent prompt.

    Target: under 700 tokens.

    Args:
        task: Current task dictionary.
        progress: Progress statistics.
        memory: Memory summary list.

    Returns:
        Minimal prompt string.
    """
    memory_str = "\n".join(
        f"- {m}" for m in memory[-2:]
    )

    return f"""# HelixCD Agent Context
Owner: ShamshabadAnil
Progress: {progress['done']}/{progress['total']} ({progress['percent']}%)

TASK: {task['id']} - {task['name']}

STACK(LOCKED):
Python3.11 | Ollama+ChromaDB+Redis+PostgreSQL
FastAPI | HTML+CSS+VanillaJS | Docker | GKE+GCR

CONNECTIONS(DOCKER - NEVER localhost):
ollama:11434 | chromadb:8000
redis:6379 | postgres:5432

RULES(NEVER BREAK):
- Type hints + docstrings on ALL functions
- Tests required (80%+ coverage)
- No secrets in code
- No React/Vue/Angular
- No placeholders or TODOs
- No localhost in Docker code

LAST SESSIONS:
{memory_str}

REPOS:
github.com/ShamshabadAnil/helixcd
github.com/ShamshabadAnil/helixcd-vision

Confirm task. Begin immediately.
End with: Run helix done"""


def generate() -> None:
    """Generate mobile data JSON file.

    Returns:
        None
    """
    print("Generating mobile data...")

    registry = VISION / "WORK_REGISTRY.md"
    task = get_next_task(registry)
    progress = get_progress(registry)
    memory = get_memory(VISION)
    prompt = build_prompt(
        task, progress, memory
    )

    data = {
        "task_id": task["id"],
        "task_name": task["name"],
        "task_status": task["status"],
        "progress_done": progress["done"],
        "progress_total": progress["total"],
        "progress_percent": progress["percent"],
        "phase": "documentation",
        "prompt": prompt,
        "memory": memory,
        "token_estimate": len(prompt) // 4,
        "updated": datetime.now().isoformat(),
        "owner": "ShamshabadAnil"
    }

    OUTPUT.parent.mkdir(
        parents=True, exist_ok=True
    )

    with open(OUTPUT, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

    print(f"[OK] data.json generated")
    print(f"     Task: {task['id']} - {task['name']}")
    print(f"     Progress: {progress['done']}/{progress['total']}")
    print(f"     Tokens: ~{len(prompt)//4}")
    print(f"     Output: {OUTPUT}")


if __name__ == "__main__":
    generate()
EOF

echo "  [OK] generate_mobile_data.py"

# ════════════════════════════════════════════════
# FILE 3 — GITHUB ACTION
# Runs automatically after helix done
# Generates fresh data.json
# Deploys to GitHub Pages
# ════════════════════════════════════════════════
echo "[DIR] Creating GitHub Pages action..."

mkdir -p "$REPO/.github/workflows"

cat > "$REPO/.github/workflows/mobile-prompt.yml" \
<< 'EOF'
name: Update Mobile Prompt Page

on:
  # Run when context files update
  push:
    branches: [main]
    paths:
      - 'AGENT_CONTEXT_PUBLIC.md'
      - 'docs/**'
      - 'scripts/generate_mobile_data.py'

  # Run on schedule (every 2 hours)
  schedule:
    - cron: '0 */2 * * *'

  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate_and_deploy:
    name: Generate Prompt + Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout helixcd
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Try to get helixcd-vision
      # Uses PAT if available
      # Falls back to public context only
      - name: Checkout helixcd-vision
        continue-on-error: true
        uses: actions/checkout@v4.1.1
        with:
          repository: ShamshabadAnil/helixcd-vision
          token: ${{ secrets.VISION_PAT || secrets.GITHUB_TOKEN }}
          path: helixcd-vision

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'

      - name: Generate data.json
        env:
          PYTHONUTF8: "1"
          PYTHONIOENCODING: "utf-8"
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python scripts/generate_mobile_data.py

      - name: Commit data.json
        run: |
          git config user.name "HelixCD Bot"
          git config user.email \
            "bot@helixcd.dev"
          git add docs/data.json
          git diff --staged --quiet || \
          git commit -m \
            "chore: update mobile prompt data"
          git push origin main

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print URL
        run: |
          echo ""
          echo "Mobile prompt page live at:"
          echo "https://ShamshabadAnil.github.io/helixcd"
          echo ""
EOF

echo "  [OK] mobile-prompt.yml"

# ════════════════════════════════════════════════
# FILE 4 — UPDATE HELIX CLI
# Add mobile URL to helix next output
# Add mobile command
# ════════════════════════════════════════════════
echo "[DIR] Updating helix CLI for mobile..."

PROXY="$WORKSPACE/helix-proxy"

cat >> "$PROXY/helix_commands.sh" << 'MOBILEEOF'

  # ── MOBILE URL ────────────────────────────
  mobile)
    echo ""
    echo "  Mobile prompt page:"
    echo "  https://ShamshabadAnil.github.io/helixcd"
    echo ""
    echo "  Open on mobile browser"
    echo "  Tap [Copy Prompt]"
    echo "  Paste into Claude or Cursor"
    echo ""

    # Try to open in browser
    open "https://ShamshabadAnil.github.io/helixcd" \
      2>/dev/null || \
    start "https://ShamshabadAnil.github.io/helixcd" \
      2>/dev/null || \
    echo "  Open URL manually on mobile"
    ;;

MOBILEEOF

echo "  [OK] mobile command added to CLI"

# ════════════════════════════════════════════════
# FILE 5 — ENABLE GITHUB PAGES
# Script to enable via API
# ════════════════════════════════════════════════
echo "[DIR] Creating Pages enabler..."

cat > "$REPO/scripts/enable-github-pages.sh" \
<< 'EOF'
#!/bin/bash
# Enable GitHub Pages for helixcd
# Run once with your GitHub token
# Usage: bash enable-github-pages.sh TOKEN

TOKEN=$1
REPO="ShamshabadAnil/helixcd"

if [ -z "$TOKEN" ]; then
  echo ""
  echo "Usage: bash enable-github-pages.sh TOKEN"
  echo ""
  echo "Get token at:"
  echo "github.com -> Settings"
  echo "-> Developer Settings"
  echo "-> Personal Access Tokens"
  echo "-> Generate with 'repo' scope"
  echo ""
  exit 1
fi

echo "Enabling GitHub Pages..."

curl -s -X POST \
  -H "Authorization: token $TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/$REPO/pages" \
  -d '{
    "source": {
      "branch": "main",
      "path": "/docs"
    }
  }' | python -c "
import json,sys
d=json.load(sys.stdin)
if 'html_url' in d:
  print(f'[OK] Pages enabled!')
  print(f'URL: {d[\"html_url\"]}')
else:
  print(f'Response: {json.dumps(d,indent=2)}')
" 2>/dev/null || echo "Check GitHub UI"

echo ""
echo "Also add VISION_PAT secret:"
echo "github.com/ShamshabadAnil/helixcd"
echo "-> Settings -> Secrets -> Actions"
echo "-> New secret: VISION_PAT"
echo "-> Value: your GitHub token"
echo ""
EOF

chmod +x "$REPO/scripts/enable-github-pages.sh"
echo "  [OK] enable-github-pages.sh"

# ════════════════════════════════════════════════
# FILE 6 — GENERATE INITIAL DATA
# Creates first data.json locally
# ════════════════════════════════════════════════
echo "[DIR] Generating initial data.json..."

export PYTHONUTF8=1
export PYTHONIOENCODING=utf-8
export GITHUB_WORKSPACE="$WORKSPACE"

python "$REPO/scripts/generate_mobile_data.py" \
  2>/dev/null || \
python3 "$REPO/scripts/generate_mobile_data.py" \
  2>/dev/null || \
echo "  [WARN] Manual generation needed"

echo "  [OK] Initial data.json generated"

# ════════════════════════════════════════════════
# COMMIT EVERYTHING
# ════════════════════════════════════════════════
echo ""
echo "[PUSH] Committing to GitHub..."

cd "$REPO"
git add .
git commit -m \
  "feat: add mobile prompt page

GitHub Pages at:
  ShamshabadAnil.github.io/helixcd

Mobile workflow:
  1. Open URL on phone
  2. See current task
  3. Tap [Copy Prompt]
  4. Open Claude/Cursor mobile
  5. Paste and work

Auto-updates:
  Every 2 hours via GitHub Actions
  After every helix done commit
  Fresh data always

Files added:
  docs/index.html (mobile page)
  docs/data.json (prompt data)
  scripts/generate_mobile_data.py
  scripts/enable-github-pages.sh
  .github/workflows/mobile-prompt.yml

Works when laptop is OFF.
No server needed.
GitHub Pages is always online." \
  --quiet 2>/dev/null || true

git push origin main --quiet 2>/dev/null || true

echo "  [OK] Pushed to GitHub"

# ════════════════════════════════════════════════
# FINAL SUMMARY
# ════════════════════════════════════════════════
echo ""
echo "============================================"
echo "  Mobile Access Setup Complete!"
echo "============================================"
echo ""
echo "MOBILE URL (after Pages enabled):"
echo "  https://ShamshabadAnil.github.io/helixcd"
echo ""
echo "MOBILE WORKFLOW:"
echo "  1. Open URL on phone"
echo "  2. See current task + prompt"
echo "  3. Tap [Copy Prompt]"
echo "  4. Open Claude or Cursor mobile"
echo "  5. Paste into chat"
echo "  6. Agent starts working"
echo ""
echo "AUTO-UPDATES:"
echo "  Every 2 hours automatically"
echo "  After every helix done"
echo "  Works when laptop is OFF"
echo ""
echo "ENABLE GITHUB PAGES NOW:"
echo "  Option 1 (script):"
echo "    bash scripts/enable-github-pages.sh TOKEN"
echo ""
echo "  Option 2 (manual):"
echo "    github.com/ShamshabadAnil/helixcd"
echo "    -> Settings -> Pages"
echo "    -> Source: main branch /docs"
echo "    -> Save"
echo ""
echo "ADD VISION_PAT SECRET:"
echo "  github.com/ShamshabadAnil/helixcd"
echo "  -> Settings -> Secrets -> Actions"
echo "  -> New: VISION_PAT = your token"
echo "  (Allows Actions to read helixcd-vision)"
echo ""
echo "TEST MOBILE:"
echo "  helix mobile"
echo "  (shows URL + opens browser)"
echo "============================================"